config/routes.rb
Rails.application.routes.draw do
  root to: "projects#index"

  resources :deploys, only: :show
  resources :projects
  resource :search, only: :show

  namespace :api do
    resources :deploys, only: :create
  end

  match '/auth/:service/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/failure', to: 'sessions#failure', via: [:get, :post]
  get '/logout', to: 'sessions#destroy'
  get "/login", to: "sessions#new", as: :login
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit < ApplicationRecord
  belongs_to :deploy
  has_one :project, through: :deploy

  validates :sha, :short_sha, presence: true
  validates :author_name, :author_email, presence: true
  validates :title, presence: true

  scope :search, ->(query) { where("sha = :term OR short_sha LIKE :term", term: "#{query}%") }
end

app/models/deploy.rb
class Deploy < ApplicationRecord
  paginates_per 20

  belongs_to :project
  has_many :commits, dependent: :destroy

  validates :revision, presence: true

  scope :sorted, -> { order(created_at: :desc) }

  after_create :queue_commit_fetching
  after_create :notify_slack

  def description
    "#{revision} on #{environment} at #{created_at.to_s(:db)}"
  end

  def fetch_commits
    return true if previous_sha.nil?
    Gitlab::CommitFetcher.new(project).fetch_commits_between(previous_sha, revision).each do |gitlab_commit|
      commits.create_with(
        short_sha: gitlab_commit["short_id"],
        author_name: gitlab_commit["author_name"],
        author_email: gitlab_commit["author_email"],
        title: gitlab_commit["title"]
      ).find_or_create_by(sha: gitlab_commit["id"])
    end
  end

  def previous_sha
    project.deploys
      .where(environment: environment)
      .where("created_at < ?", created_at)
      .order(created_at: :desc)
      .first.try(:revision)
  end

  def where
    where = environment
    where += " on #{location}" if location.present?
    where
  end

private

  def queue_commit_fetching
    return true if project.external_api_key.blank?
    CommitFetcherJob.perform_later(self)
  end

  def notify_slack
    SlackPosterJob.perform_later(self)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  paginates_per 20

  has_many :deploys, dependent: :destroy
  has_many :commits, through: :deploys

  validates :name, presence: true

  before_create :generate_api

  scope :search, ->(query) { where("name LIKE ?", "%#{query}") }

  def gitlab_id
    # We have to encode the slash between the namespace and the project
    # do be able to use this in the api.
    URI.parse(repo).path.sub(/^\//, "").gsub(/\//, "%2F")
  end

  def gitlab_url
    parsed_uri = URI.parse(repo)
    [parsed_uri.scheme, "://", parsed_uri.host].join
  end

private

  def generate_api
    token = SecureRandom.urlsafe_base64(20).tr('lIO0', 'sxyz')
    while(Project.exists?(api_key: token)) do
      token = SecureRandom.urlsafe_base64(20).tr('lIO0', 'sxyz')
    end
    self.api_key = token
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, :uid, presence: true
end

app/controllers/api/deploys_controller.rb
class Api::DeploysController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :user_required!

  before_action :fetch_project

  def create
    deploy = @project.deploys.new(
      revision: params[:revision],
      deployer: params[:deployer],
      environment: params[:environment],
      location: params[:location]
    )
    if deploy.save
      render json: { message: "Successfully logged deploy" }, status: 200
    else
      render json: deploy.errors.messages.to_json, status: 500
    end
  end

private

  def fetch_project
    @project ||= Project.find_by(api_key: params[:project_key])
    unless @project.present?
      return render(json: { message: "Project not found" }, status: 404)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :user_required!

  def home
    render "sessions/new"
  end

protected

  def user_required!
    return true if current_user
    redirect_to [:login, redirect_to: request.fullpath], error: "You need to be logged in!"
  end

  def current_user
    return false unless session[:user_id].present?
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user
end

app/controllers/deploys_controller.rb
class DeploysController < ApplicationController
  def show
    @deploy = Deploy.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.page(params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @deploys = @project.deploys.sorted.page(params[:page])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(
        :name,
        :repo,
        :external_api_key,
        :slack_token,
        :slack_channel
      )
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @commits = Commit.search(params[:query])
    @projects = Project.search(params[:query])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :user_required!, only: [:new, :create, :failure, :login]

  def new
  end

  def create
    auth_hash = request.env["omniauth.auth"]
    user = User.create_with(
      email: auth_hash.info.email,
      name: auth_hash.info.email.split("@").first
    ).find_or_create_by!(uid: auth_hash.uid)
    session[:user_id] = user.id
    redirect_to request.env["omniauth.origin"] || :root
  end

  def failure
    render plain: "failure!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/deploys/show.html.haml
.breadcrumb
  = link_to "Projecten", [:projects]
  = link_to @deploy.project.name, @deploy.project
  = link_to @deploy.revision, @deploy

.info
  %dl
    %dt When
    %dd= @deploy.created_at.to_s(:db)
    %dt What
    %dd= @deploy.revision
    %dt Where
    %dd= @deploy.where
    %dt Who
    %dd= @deploy.deployer

%h3 Commits deployed
%table
  %thead
    %tr
      %th.narrow Revision
      %th Author
      %th Title
  %tbody
    - @deploy.commits.each do |commit|
      %tr
        %td= link_to commit.short_sha, "#{@deploy.project.repo}/commit/#{commit.sha}", target: :_blank
        %td #{commit.author_name} (#{commit.author_email})
        %td= commit.title

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Deploylog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #main
      %h1= link_to "Deploylogger", :root
      - if current_user
        .search
          = form_tag :search, url: :searches, method: :get, html: { role: "search" } do
            .search-input
              = text_field_tag :query, params[:query], placeholder: :search
            .search-submit
              = submit_tag "Search"
      = yield

app/views/projects/_form.html.haml
= form_for(project) do |f|
  - if project.errors.any?
    #error_explanation
      %h2
        = pluralize(project.errors.count, "error")
      prohibited this project from being saved:
    %ul
      - project.errors.full_messages.each do |message|
        %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :repo
    = f.text_field :repo
  .field
    = f.label :external_api_key
    = f.text_field :external_api_key
  .field
    = f.label :slack_token
    = f.text_field :slack_token
  .field
    = f.label :slack_channel
    = f.text_field :slack_channel
  .actions
    = f.submit

app/views/projects/edit.html.haml
.breadcrumb
  = link_to "Projects", :projects
  = link_to "Change #{@project.name}", "javascript:void(0)"

= render 'form', project: @project
= link_to 'Cancel', @project

app/views/projects/index.html.haml
%p#notice= notice
.breadcrumb
  = link_to "Projects", :projects

.container
  - @projects.each do |project|
    .project
      .project-title= link_to project.name, project
      .project-body
        .stats
          %ul
            %li
              #{project.deploys.count}
              %span deploys
            %li
              #{project.commits.count}
              %span commits
            %li
              = project.deploys.select(:deployer).distinct.count
              %span deployers
            %li
              = project.deploys.select(:environment).distinct.count
              %span environments
        - if project.deploys.any?
          Latest deploy:
          = link_to project.deploys.last.created_at, project.deploys.last
        - else
          Never deployed yet.
    %hr/
  = paginate @projects
%br/
= link_to 'Add Project', new_project_path

app/views/projects/new.html.haml
.breadcrumb
  = link_to "Projects", :projects
  = link_to "Add project", "javascript:void(0)"

= render 'form', project: @project

= link_to '<- All projects', projects_path

app/views/projects/show.html.haml
%p#notice= notice
.breadcrumb
  = link_to "Projects", [:projects]
  = link_to @project.name, @project

.info
  %dl
    %dt Repo:
    %dd= @project.repo
    %dt Api key:
    %dd= @project.api_key
  = link_to 'Change', edit_project_path(@project)

%h3 Deploys
%table
  %thead
    %tr
      %th Deploy
      %th.narrow Revision
      %th.narrow Commits
      %th Env
      %th Location
      %th Deployer
  %tbody
    - @deploys.each do |deploy|
      %tr
        %td= link_to deploy.created_at.to_s(:db), deploy
        %td= link_to deploy.revision[0..7], deploy
        %td= deploy.commits.count
        %td= deploy.environment
        %td= deploy.location
        %td= deploy.deployer
= paginate @deploys

app/views/searches/show.html.haml
.breadcrumb
  = link_to "Search", "javascript:void(0)"
  = link_to params[:query], "javascript:void(0)"

%h2 Found projects
%table
  %thead
    %tr
      %th Project
      %th Repo
      %th Last deploy
  %tbody
    - if @projects.none?
      %tr
        %td{ colspan: 3 } No projects found
    - @projects.each do |project|
      %tr
        %td= link_to project.name, project
        %td= project.repo
        %td= link_to project.deploys.last.description, project.deploys.last

%h2 Found commits
%table
  %thead
    %tr
      %th Project
      %th Deploy
      %th What
      %th When
      %th Where
      %th Who
  %tbody
    - if @commits.none?
      %tr
        %td{ colspan: 6 } No commits found
    - @commits.each do |commit|
      %tr
        %td= link_to commit.project.name, commit.project
        %td= link_to commit.deploy.revision[0..7], commit.deploy
        %td= commit.title
        %td= commit.deploy.created_at.to_s(:db)
        %td= commit.deploy.environment
        %td= commit.author_name